[general]
import = [
  # "./catppuccin.toml",
  "./duskfox.toml",
  # "./nightfox.toml",
]

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
# There is no winning with this stupid ass monitor...
# Yeah I need some kind of size aware resizing low key.
size = 10.0

[window]
decorations = "None"
# Doesn't make very much sense with niri as it stands
# opacity = 0.85
# startup_mode = "Fullscreen"

[terminal.shell]
program = "/usr/bin/fish"
args = ["-l"]


[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[env]
TERM = "alacritty"
LC_CTYPE = "en_US.UTF-8"
